version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./tmp/db:/var/lib/mysql
  web:
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: sh db/wait_for_mysql.sh bundle exec rails s -p 3000 -b '0.0.0.0'
    stop_signal: SIGINT
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
