version: 2
jobs:
  build:
    machine:
      services:
        - docker
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:13306 -timeout 1m
      - run:
          name: "before_test: setup db"
          command: docker-compose run web rails db:create db:migrate
      - run:
          name: test
          command: docker-compose run web rails test
      - run:
          name: docker-compose down
          command: docker-compose down
